/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        fredoka: ['"Fredoka One"', 'cursive'],
        nunito:  ['Nunito', 'sans-serif'],
      },
      colors: {
        primary: { DEFAULT:'#3B82F6', dark:'#1D4ED8', light:'#EFF6FF', border:'#93C5FD' },
        ok:      { DEFAULT:'#22C55E', dark:'#15803D', light:'#DCFCE7' },
        bad:     { DEFAULT:'#EF4444', dark:'#B91C1C', light:'#FEE2E2' },
        star:    { DEFAULT:'#F59E0B', dark:'#B45309' },
        ink:     { DEFAULT:'#1E293B', muted:'#64748B', faint:'#CBD5E1' },
        surface: '#F8FAFF',
      },
      keyframes: {
        float:        { '0%,100%':{ transform:'translateY(0)' }, '50%':{ transform:'translateY(-6px)' } },
        bobble:       { '0%,100%':{ transform:'translateY(0) rotate(0)' }, '30%':{ transform:'translateY(-14px) rotate(-5deg)' }, '60%':{ transform:'translateY(-6px) rotate(4deg)' } },
        dance:        { '0%':{ transform:'translateY(0) rotate(-7deg) scale(1)' }, '100%':{ transform:'translateY(-16px) rotate(7deg) scale(1.07)' } },
        blink:        { '0%,90%,100%':{ transform:'scaleY(1)' }, '95%':{ transform:'scaleY(0.08)' } },
        popIn:        { from:{ transform:'scale(0)', opacity:'0' }, to:{ transform:'scale(1)', opacity:'1' } },
        slideUp:      { from:{ transform:'translateY(30px)', opacity:'0' }, to:{ transform:'translateY(0)', opacity:'1' } },
        shake:        { '0%,100%':{ transform:'translateX(0)' }, '25%':{ transform:'translateX(-8px)' }, '75%':{ transform:'translateX(8px)' } },
        twinkle:      { '0%,100%':{ opacity:'.3', transform:'scale(.8)' }, '50%':{ opacity:'1', transform:'scale(1.2)' } },
        cloudDrift:   { from:{ left:'-250px' }, to:{ left:'110vw' } },
        sunPulse:     { '0%,100%':{ boxShadow:'0 0 50px 20px rgba(251,191,36,.3)' }, '50%':{ boxShadow:'0 0 80px 40px rgba(251,191,36,.5)' } },
        shimmer:      { '0%':{ left:'-80%' }, '100%':{ left:'140%' } },
        splashDrop:   { from:{ transform:'translateY(-120px) scale(.5)', opacity:'0' }, to:{ transform:'translateY(0) scale(1)', opacity:'1' } },
        splashHide:   { to:{ transform:'translateY(-100%)', opacity:'0' } },
        attractPulse: { '0%,100%':{ opacity:'.4', transform:'scale(.95)' }, '50%':{ opacity:'1', transform:'scale(1.05)' } },
        comboPop:     { '0%':{ transform:'translate(-50%,-50%) scale(0)', opacity:'0' }, '40%':{ transform:'translate(-50%,-50%) scale(1.3)', opacity:'1' }, '100%':{ transform:'translate(-50%,-50%) scale(.7)', opacity:'0' } },
        flashIn:      { '0%':{ opacity:'.6' }, '100%':{ opacity:'0' } },
        toastIn:      { from:{ opacity:'0', transform:'translateX(-50%) translateY(16px)' }, to:{ opacity:'1', transform:'translateX(-50%) translateY(0)' } },
        nodeGlow:     { '0%,100%':{ boxShadow:'0 0 0 0 rgba(59,130,246,.3)' }, '50%':{ boxShadow:'0 0 0 10px rgba(59,130,246,0)' } },
        sway:         { '0%,100%':{ transform:'rotate(-3deg)' }, '50%':{ transform:'rotate(3deg)' } },
        floatUp:      { '0%':{ transform:'translateY(0) rotate(0)', opacity:'1' }, '100%':{ transform:'translateY(-200px) rotate(45deg)', opacity:'0' } },
        fadeIn:       { from:{ opacity:'0' }, to:{ opacity:'1' } },
      },
      animation: {
        'robi-float':    'float 3s ease-in-out infinite',
        'robi-bobble':   'bobble 1.8s ease-in-out infinite',
        'robi-dance':    'dance .55s ease-in-out infinite alternate',
        'robi-blink':    'blink 4s ease-in-out infinite',
        'pop-in':        'popIn .4s cubic-bezier(.34,1.56,.64,1)',
        'slide-up':      'slideUp .35s ease',
        'shake':         'shake .35s ease',
        'twinkle':       'twinkle 2.5s ease-in-out infinite',
        'cloud-drift':   'cloudDrift linear infinite',
        'sun-pulse':     'sunPulse 4s ease-in-out infinite',
        'shimmer':       'shimmer 2.2s ease-in-out infinite',
        'splash-drop':   'splashDrop .8s cubic-bezier(.34,1.56,.64,1)',
        'splash-hide':   'splashHide .6s cubic-bezier(.76,0,.24,1) forwards',
        'attract-pulse': 'attractPulse 1.4s ease-in-out infinite',
        'combo-pop':     'comboPop .85s ease forwards',
        'flash-in':      'flashIn .4s ease forwards',
        'toast-in':      'toastIn .35s ease',
        'node-glow':     'nodeGlow 2s ease-in-out infinite',
        'sway':          'sway 3s ease-in-out infinite',
        'float-up':      'floatUp 1.2s ease forwards',
        'fade-in':       'fadeIn .4s ease',
      },
    },
  },
  plugins: [],
};
